### ISSUE TITLE
glob does not accept non-unicode patterns

### ISSUE THREAD

**Issue by droundy** [rust-lang-nursery/glob#58]
The `str` input of glob precludes its use with user-defined patterns that may be non-unicode.  The package seems to strongly reject the idea that there might be other filenames out there that might need to be matched against.  Perhaps there should be a separate package for globbing with `OsStr`?

**Comment by BurntSushi** [comment]
@droundy I think this might be a dupe of #23?

The [`globset`](https://docs.rs/globset) crate supports *matching* non-UTF-8 file paths (e.g., `*` can match the byte `\xFF`), but it doesn't support providing non-UTF-8 globs themselves. However, since that crate is built on `regex`, it shouldn't be *that* hard to graft support for it into `globset` proper without touching the matching internals.

**Comment by droundy** [comment]
I don't think it's a dupe of #23, since this would be about creating a glob with non-utf8 content, e.g. if I wanted to enable user provided globs, git does with .gitignore.

**Comment by BurntSushi** [comment]
@droundy #23 mentions that though...

> Not only are its patterns restricted to strings

> glob() needs to accept both strings and byte-vectors. It can do this using std::path::BytesContainer

> glob() needs to process its pattern as a byte vector instead of a string

**Comment by droundy** [comment]
Ah, I had been tricked be the title.  Yes, this is a dupe.
