### ISSUE TITLE
Single star `*` matches any number of subdirectories in `Pattern`

### ISSUE THREAD

**Issue by pkolaczk** [rust-lang-nursery/glob#96]
I wanted to use only the `Pattern` functionality from glob to do pattern matching on paths, because my project uses its own code to walk the directory tree. However, I'm surprised that actually a pattern `*` matches many path components, not just one. If this is by design, I wonder, what usefullness it really brings and why is there any distinction between `**` and `*` ? 

These patterns seem to be equivalent:
`dir1/*/file`
`dir1/**/file`

I'd expect `dir1/*/file`  to match `dir1/dir2/file` but not match `dir1/dir2/dir3/file`, but that's not the case.

**Comment by BurntSushi** [comment]
Sounds like you want to enable the `require_literal_separator` option: https://docs.rs/glob/0.3.0/glob/struct.MatchOptions.html

**Comment by mattferrin** [comment]
Your project is awesome. This caused the most confusing bug for me though because my first unit tests were on my code rather than this glob library. None of the general online documentation for general globbing shows the behavior this library has when it defaults `require_literal_separator` to false. It should probably be defaulted to `true`.

**Comment by BurntSushi** [comment]
@mattferrin Having `require_literal_separator` false by default is pretty standard. For example, in Python:

```
>>> import fnmatch
>>> fnmatch.fnmatch('foo/bar/baz', 'fo*az')
True
```

**Comment by mattferrin** [comment]
I haven't done tons and tons of globbing and the globbing I have done had always been JavaScipt, so I'll take your word for it. Thank you!
