### ISSUE TITLE
Clarify file order / sorting

### ISSUE THREAD

**Issue by vojtechkral** [rust-lang-nursery/glob#98]
Hi,
    I'm was wondering in what order the paths from glob patterns are when I iterate over them, ie. whether they are in a well-defined order or if the order is arbitrary. I assume it's the latter, but I couldn't find a mention in the docs.
Thanks!

**Comment by slluk** [comment]
Hi,
I just had the same wondering.
Since the time, you probably found the answer, but for others:
At the bottom of the [glob definition page](https://docs.rs/glob/0.3.0/glob/fn.glob.html):
"Paths are yielded in alphabetical order."

This is important as the behavior seems to be different across languages: sorted by default in C but not in Python.

**Comment by vojtechkral** [comment]
Cool, thank you.
